services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    env_file:
      - ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    env_file:
      - ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    env_file:
      - ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    env_file:
      - ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"