
# version of docker compose we are using
version: '3.8'

services:
# bulid the docker image from the api gateway directory
  api-gateway:
    build: ./api-gateway
# Expose the port 3000 on the host and map it to port 3000 in container
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
  # this api gateway depends on which services
    depends_on:
      - redis
      - rabbitmq
      # environment that we are going to use
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5